version: '3.8'

services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: test-app-backend
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: production
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - frontend
    networks:
      - test-app-network

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: test-app-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:3005/api
    networks:
      - test-app-network

networks:
  test-app-network:
    driver: bridge 